#! /bin/sh

# apt postinst, based liberally on James Troup's gpm postinst
# Copyright (C) 1998, Ben Gertzfield <che@debian.org>

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

set -e

#DEBHELPER#

case "$1" in
       configure)
esac
